# -*- coding: utf-8 -*-
"""emails.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dR-tbbSU937eWccMln978mR_e0PHgczJ
"""

import pandas as pd
phishing_keywords = ["urgent", "password reset", "bank", "verify", "account suspended"]

emails = pd.read_csv("/content/email_exercises - emails_exercises.csv")
if 'Content' in emails.columns:
  emails['is_phishing'] = emails['Content'].apply(
      lambda x: any(keyword in str(x).lower() for keyword in phishing_keywords)
  )
  emails.to_csv("/content/25011575_phishing.csv", index=False)
  print("Phishing detection complete. ✅")
else:
  print("Error: The 'content' column is missing from the dataset.")