# -*- coding: utf-8 -*-
"""hate_speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgQwwEX6Uz99y-vcnFfrCMx3DfBsPayh
"""

offensive_words = [
    "inyenzi", "cockroaches", "kill", "exterminate", "destroy",
    "traitors", "snakes", "rats", "hutu power", "tutsi",
    "ethnic cleansing", "wipe out", "enemy", "revenge",
    "impurity", "traitors", "infiltrators", "parasites"
]

with open("/content/speech.txt") as speech:
  text=speech.read()
def detect_hate_speech(text):
    detected_words = [word for word in offensive_words if word in text.lower()]
    return detected_words
hate_words = detect_hate_speech(text)
if hate_words:
    print("Hate speech detected! Offensive words:", hate_words)
else:
    print("No hate speech detected.")